### PR TITLE
fix: 58 postprocessing breaks on nuxt

### LINKED ISSUE #58: Postprocessing breaks on Nuxt
**Describe the bug**
Postprocessing Render seems to break on Nuxt.

**Reproduction**
https://stackblitz.com/edit/nuxt-starter-2qaqwx?file=nuxt.config.ts,components%2FTheExperience.vue,package.json,app.vue

**Steps**
1. Go to Reproduction
2. Resize

**Reproduction**
When resizing the clear color also goes blank. Effects don't work etc

**Expected behavior**
All smooth and working lol

**Screenshots**
Screenshot 2023-09-27 at 13 26 13

**System Info**
Output of `npx envinfo --system --npmPackages '{vite,@tresjs/*, three, vue}' --binaries --browsers` 

```
  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.20.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.6.10 - /usr/local/bin/pnpm
  npmPackages:
    @tresjs/nuxt: ^1.1.7 => 1.1.7 
    @tresjs/post-processing: ^0.4.0 => 0.4.0 
```

**Additional context**

### PR DESCRIPTION
**Pull request by alvarosabu**
Closes #58

### CODE REVIEW

File: src/core/EffectComposer.vue [hunk 1]
```diff
@@ -111,6 +111,11 @@ onLoop(({ delta }) => {
 onUnmounted(() => {
   effectComposer.value?.dispose()
 })
+
+onMounted(() => {
+  if (!sizes.height.value && !sizes.width.value) return
+  if (props.enabled) initEffectComposer()
```
Comment (Tinoooo) [inline src/core/EffectComposer.vue:117]:
```suggestion
  if (sizes.height.value && sizes.width.value && props.enabled) {
    initEffectComposer()
    stop()
  }
```

Caution: I did not test the suggestion 😄

**Review by Tinoooo — CHANGES_REQUESTED** [review]

**Comment by alvarosabu** [comment]
Tested your approach and all good, should we merge it then?

**Comment by Tinoooo** [comment]
> Tested your approach and all good, should we merge it then?

Yes 💪
I'll do it.

**Review by Tinoooo — APPROVED** [review]
