### PR TITLE
fix: avoid  recursive updates when resizing the window

### LINKED ISSUE #80: [Nuxt - Astro] Maximum recursive updates exceeded on window resize
**Describe the bug**
A scene using `EffectComposer` gets broken when resizing the screen

**Reproduction**
[Reproduction](https://stackblitz.com/edit/nuxt-starter-hzbvpr?file=nuxt.config.ts,app.vue,components%2FModel.vue)

**Steps**
2. Resize Scene

**Expected behavior**
Scene with post-processing doesn't break

**Screenshots**

https://github.com/Tresjs/post-processing/assets/4699008/ce16b034-1b7b-49df-a708-320cf13c9831

**System Info**
Output of `npx envinfo --system --npmPackages '{vite,@tresjs/*, three, vue}' --binaries --browsers` 

```
  System:
    OS: macOS 14.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 89.77 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.14.1 - ~/.nvm/versions/node/v18.14.1/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.3.1 - ~/.nvm/versions/node/v18.14.1/bin/npm
  Browsers:
    Brave Browser: 118.1.59.124
    Chrome: 119.0.6045.105
    Firefox: 118.0.1
    Safari: 17.1
  npmPackages:
    @tresjs/cientos: ^3.6.0 => 3.6.0 
    @tresjs/leches: 0.14.0-next.0 => 0.14.0-next.0 
    @tresjs/nuxt: ^1.2.2 => 1.2.2 
    @tresjs/post-processing: 0.6.0 => 0.6.0 
```
**Additional context**

### PR DESCRIPTION
**Pull request by alvarosabu**
Fixes #80

### CODE REVIEW

File: src/core/EffectComposer.vue [hunk 1]
```diff
@@ -82,20 +77,16 @@ const effectComposerParams = computed(() => {
 const initEffectComposer = () => {
   if (!renderer.value && !scene.value && !camera.value) return
 
-  effectComposer.value = new EffectComposerImpl(renderer.value, effectComposerParams.value)
-  effectComposer.value.addPass(new RenderPass(scene.value, camera.value))
+  effectComposer.value = new EffectComposerImpl(unref(renderer), effectComposerParams.value)
+  effectComposer.value.addPass(new RenderPass(unref(scene), unref(camera)))
```
Comment (Tinoooo) [inline src/core/EffectComposer.vue:81]: Does the change to use unref here have any advantage?

File: src/core/EffectComposer.vue [hunk 2]
```diff
@@ -82,20 +77,16 @@ const effectComposerParams = computed(() => {
...
-
-stop = watch([sizes.height, sizes.width], () => {
+watch(() => [sizes.height.value, sizes.width.value], ([width, height]) => {
   // effect composer should only live once the canvas has a size > 0
-  if (!sizes.height.value && !sizes.width.value) return
-
-  watchEffect(initEffectComposer)
-  stop?.()
+  if (!width && !height) return
+  effectComposer.value ? effectComposer.value.setSize(sizes.width.value, sizes.height.value) : initEffectComposer()
```
Comment (Tinoooo) [inline src/core/EffectComposer.vue:89]: Without the watchEffect, scene or camera changes are not properly handled.
