### PR TITLE
fix!: unified-exports-suffix-pmndrs-effects

### LINKED ISSUE #147: Broken imports in v1.0.0 w/ Nuxt
Attempting to use the 1.0.0 release with Nuxt, I get an error on the `nuxt prepare` step. This is reproducible within this repo's nuxt playground if you update the dependency to 1.0.0.

```
 ERROR  ENOENT: no such file or directory, open '/Users/.../.../post-processing/playground-nuxt/@tresjs/post-processing'                                                             10:29:39 AM
 ```

This does not happen when using `1.0.0-next.1`.

```
- Operating System: Darwin
- Node Version:     v20.10.0
- Nuxt Version:     3.14.1592
- CLI Version:      3.15.0
- Nitro Version:    2.10.4
- Package Manager:  npm@10.8.3
- Builder:          -
- User Config:      default
- Runtime Modules:  @nuxt/eslint@0.7.2, @pinia/nuxt@0.7.0, @nuxtjs/supabase@1.4.3, @primevue/nuxt-module@4.2.4, @nuxtjs/tailwindcss@6.12.2, nuxt-lodash@2.5.3, @nuxt/icon@1.8.2, @tresjs/nuxt@3.0.7
- Build Modules:    -
```

Thanks for maintaining this project!

### PR DESCRIPTION
**Pull request by alvarosabu**
This PR fixes the name collision and type issues:

- Consolidates post-processing effects under a unified namespace (`@tresjs/post-processing`). Pmndrs `EffectComposer` is now `EffectComposerPmndrs`, same for all the effects and composables under `src/core/pmndrs`  to avoid name collisions 
- Removes local nuxt playground
- Update docs

Closes #147

### CODE REVIEW

File: docs/.vitepress/config.ts [hunk 1]
```diff
@@ -88,7 +88,7 @@ export default defineConfig({
     },
     resolve: {
       alias: {
-        '@tresjs/post-processing/three': resolve(__dirname, '../../src/core/three'),
+        '@tresjs/post-processing': resolve(__dirname, '../../src/core/three'),
         '@tresjs/post-processing/pmndrs': resolve(__dirname, '../../src/core/pmndrs'),
```
Comment (Tinoooo) [inline docs/.vitepress/config.ts:92]: I think this should be a different path and the pmndrs alias should be omitted. I changed that. Please resolve if the changes are okay for you.

**Review by Tinoooo — APPROVED** [review]
